name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM deps based on the package-lock.json file.


inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir:
    description: Application working directory
    default: '.'
    required: false
  target-env:
    description: Controlles wheather dev deps are installed
    default: dev
    required: false

  



runs:
  # This define the type of custom action:
  using: composite
  steps:
    - name: Setup NodeJS Version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ inputs.target-env }}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
    
    - name: Install Dependencies
      # Dependencies will be installed only if not allready on cache:
      if: ${{ steps.cache.outputs.cache-hit != 'true'}}
      # Then, this checks if the target environment is dev and will install deps. If not - it will not install dev dependencies !
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      # Required to indicate a shell and working dir when running a step in composite custom action:
      shell: bash
      working-directory: ${{ inputs.working-dir }}

  




    

    






    




        
        


    




