name: 05 - 2 - Event Filters and Activity Types

on:
    pull_request:
        types:
            - closed
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is closed or synchronized AND base branch is main"




