name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env -  ${{ inputs.target-env }}

on:
    workflow_dispatch:
        # Select the environment type to dictate the dependencis installation behaiviour
        # This will be passed to the custom action created earlier.
        inputs:
            target-env:
                description: Target Environmnet
                type: choice
                options:
                    - dev
                    - prod

                


env:
    working-directory: 17-Custom-Actions/react-app

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            # Define default working directory for all run commands.
            run:
                working-directory: ${{ env.working-directory }}

        steps:
            # To allow this workflow to use custom action defind in the current repo we must use the checkout action first:
            
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Node and NPM Deps
              id: setup-deps # This id is required to enable other steps to access it.
              # Relative path to the custom action folder:
              uses: ./.github/actions/composite-cache-deps
              with:
                # Passing Input variables to the custom action:
                node-version: 20.x
                # Need to use here again as this is not a run command:
                working-dir: ${{ env.working-directory }}
                # Takes the target invironment to determin if to install Dev dependencies:
                target-env: ${{ inputs.target-env }}

            - name: Print setup deps output
              # Using the output from the previous custom actions:
              run: |
                  echo "Installed Dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"

            
            - name: Test
              run: npm run test
              

            - name: Build
              run: npm run build
             




            