name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS

on:
    workflow_dispatch:



jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            
            # To allow this workflow to use custom action defind in the current repo we must use the checkout action first:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Check for Dependency Updates
              # Relative path to the custom action folder:
              uses: ./.github/actions/js-dependency-update
              
              



            