name: 17 - 3 - Custom Actions - Docker

on:
    workflow_dispatch:
        inputs:
            url:
                description: Url 
                type: string
                default: https://www.google.com
              
        

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            
            # To allow this workflow to use custom action defind in the current repo we must use the checkout action first:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Ping URL
              # Relative path to the custom action folder:
              uses: ./.github/actions/docker-ping-utl

              # Pass the Inputs to the custom action
              with:
                url: ${{ inputs.url }}



               

              




            