name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | BB - ${{ inputs.base-branch }} TB - ${{ inputs.target-branch }} WD - ${{ inputs.working-dir }}

on:
    workflow_dispatch:
        inputs:
            base-branch:
                description: The base branch TO which we will merge updated packages
                type: string
                default: main
            target-branch:
                description: The target branch FROM which we will merge updated packages
                type: string
                default: update-dependencies
            working-dir:
                description: Working directiory of the react application
                type: string
                default: 17-Custom-Actions/react-app

            debug:
                description: Toggels Debug mode
                type: boolean
                default: false



# Allow JS_ACTION_TOKEN / or GITHUB_TOKEN to write to the repo and create pull requests (C20)
permissions: 
    contents: write
    pull-requests: write


jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            
            # To allow this workflow to use custom action defind in the current repo we must use the checkout action first:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Check for Dependency Updates
              # Relative path to the custom action folder:
              uses: ./.github/actions/js-dependency-update
              # Pass the Inputs to the custom action
              with:
                base-branch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.target-branch }}
                working-directory: ${{ inputs.working-dir }}
                debug: ${{ inputs.debug }}

                # JS_ACTION_TOKEN is a GH Actions Variable (Secret) holding a PAT with write permissions to the repo.
                # See The corresponding Google Doc for instructions how to create this.
                gh-token: ${{ secrets.GITHUB_TOKEN }}


              




            