name: 17 - 3 - Custom Actions - Docker

on:
    workflow_dispatch:
        inputs:
            url:
                description: Url 
                type: choice
                options:
                  - https://www.google.com
                  - https://www.googsdsdasdsfgdfg4le.com
                  - invalid-formatQAZZWSXEDC

            max_trails:
                description: Maximum number of trails until action fails.
                default: '10'
                required: false
            delay:
              description: Delay in seconds between trails
              default: '5'
              required: false
              
        

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            
            # To allow this workflow to use custom action defind in the current repo we must use the checkout action first:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Ping URL
              # Relative path to the custom action folder:
              uses: ./.github/actions/docker-ping-url

              # Pass the Inputs to the custom action
              with:
                url: ${{ inputs.url }}
                max_trails: ${{ inputs.max_trails }}
                delay: ${{ inputs.delay }}

          



               

              




            